### ISSUE TITLE
the format of evidence in feverous_scorer

### ISSUE THREAD

**Issue by ginaaunchat** [Raldir/FEVEROUS#10]
I was trying the feverous_scorer in evaluation and got confused about the format of "predicted_evidence" and "evidence". 

1. In function "check_predicted_evidence_format", 
```
assert all(len(prediction) == 3
                   for prediction in instance["predicted_evidence"]), \
```

indicates that the "predicted_evidence" is a set of evidence pieces in length of 3.
But the required format of evidence in http://fever.ai is a list (at maximum three) of evidence sets.
Should the "predicted_evidence" be flattened before processing feverous_scorer?

2. In function "is_strictly_correct", 
```
for evience_group in instance["evidence"]:
       #Filter out the annotation ids. We just want the evidence page and line number
       actual_sentences = [[e[0], e[1], e[2]] for e in evience_group]
       #Only return true if an entire group of actual sentences is in the predicted sentences

       if all([actual_sent in instance["predicted_evidence"] for actual_sent in actual_sentences]):
           return True
```

indicates that the "actual_sentences" set contains evidence pieces in the format: (page,type,main_position).
But the "evidence" in development set is a list of evidence sets, actual_sentences would not retrieve evidence pieces in the format: (page,type,main_position).
Also, assume that actual_sentences contains evidence pieces in the format: (page,type,main_position), while the evidence pieces of "predicted_evidence" in the format: (page,type,position), it doesn't seem to return any true point.

Could you clarify the format of "predicted_evidence" and "evidence" for feverous_scorer?

**Comment by Raldir** [comment]
Hi,

The format of the predicted evidence is different from the gold evidence in the development/training data. For predictions, you only have to provide a single list of extracted evidence (since you are not asked to predict every gold set correctly, predicting a single complete one is sufficient). Each element in that list however, needs to be formatted as a triple, as you described in your post. Have a look at `baseline_output\dev.combined.not_precomputed.p5.s5.t3.cells.verdict.submission.jsonl`. This shows you how predicted evidence should be formatted for the submission platform. To run the file `feverous_scorer.py` yourself locally, simply call the file `dev.combined.not_precomputed.p5.s5.t3.cells.verdict.jsonl` on the evaluation script `evaluation/evaluate.py`.

**Comment by ginaaunchat** [comment]
Thank you for the explanation.
Another question about the submission. I tried the submission system on EvalAI platform with the submission file you provided as a private submission for Dev phase, but it doesn't show on the Leaderboard. Even I change it to public, it still doesn't show. In this case, how do I know if I successfully upload with correct format?

**Comment by Raldir** [comment]
The workers were restarting it seems. The submission is online on the leaderbord now!
